<template>
  <div>
    <PageHeader title="Behavioural Intelligence" subtitle="AI-driven signals turn raw behaviour into context-aware nudges.">
      <template #actions>
        <button @click="runDetect" :disabled="busy.detect" class="btn-secondary">
          <Icon name="refresh" class="w-4 h-4" :class="busy.detect ? 'animate-spin' : ''"/>{{ busy.detect ? 'Scanning…' : 'Rescan signals' }}
        </button>
        <button @click="runRecommend" :disabled="busy.reco || !openSignals.length" class="btn-primary">
          <Icon name="send" class="w-4 h-4"/>{{ busy.reco ? 'Thinking…' : 'Generate AI recommendations' }}
        </button>
      </template>
    </PageHeader>

    <div class="p-8 space-y-6">
      <TestModeStrip what="Signals &amp; AI" message="Signals fire from sandbox events and recommendations are generated by Claude but not delivered. Safe to explore."/>
      <ChannelReadiness :channels="readinessChannels"/>

      <div class="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <div class="card p-5">
          <div class="text-xs font-semibold text-ink-500 uppercase tracking-wider">Open signals</div>
          <div class="mt-2 text-3xl font-bold text-ink-900">{{ stats.open }}</div>
          <div class="text-xs text-ink-500">Active behaviours awaiting a nudge.</div>
        </div>
        <div class="card p-5">
          <div class="text-xs font-semibold text-ink-500 uppercase tracking-wider">Customers flagged</div>
          <div class="mt-2 text-3xl font-bold text-ink-900">{{ stats.customers }}</div>
          <div class="text-xs text-ink-500">Unique people with at least one open signal.</div>
        </div>
        <div class="card p-5">
          <div class="text-xs font-semibold text-ink-500 uppercase tracking-wider">AI recommendations</div>
          <div class="mt-2 text-3xl font-bold text-ink-900">{{ stats.recos }}</div>
          <div class="text-xs text-ink-500">Ready to review or drop into a campaign.</div>
        </div>
        <div class="card p-5">
          <div class="text-xs font-semibold text-ink-500 uppercase tracking-wider">Converted last 30d</div>
          <div class="mt-2 text-3xl font-bold text-accent-500">{{ stats.converted }}</div>
          <div class="text-xs text-ink-500">Signals that led to a meaningful action.</div>
        </div>
      </div>

      <div class="grid lg:grid-cols-3 gap-6">
        <div class="card p-6 lg:col-span-2">
          <div class="flex items-center justify-between mb-4">
            <div>
              <div class="font-semibold text-ink-900">Top signal categories</div>
              <div class="text-xs text-ink-500">Where your customers are right now.</div>
            </div>
          </div>
          <div v-if="!categoryBreakdown.length" class="text-sm text-ink-500 py-6 text-center">
            No signals yet. Click <span class="font-medium">Rescan signals</span> to detect behaviour from the last 30 days.
          </div>
          <div v-else class="space-y-3">
            <div v-for="c in categoryBreakdown" :key="c.key" class="flex items-center gap-3">
              <div class="w-28 text-xs font-medium capitalize text-ink-700">{{ c.key }}</div>
              <div class="flex-1 h-2 rounded-full bg-ink-100 overflow-hidden">
                <div class="h-full" :style="{ width: (c.count/maxCategory*100)+'%', background: c.color }"></div>
              </div>
              <div class="w-10 text-right text-xs font-bold text-ink-900">{{ c.count }}</div>
            </div>
          </div>
        </div>

        <div class="card p-6">
          <div class="font-semibold text-ink-900 mb-1">Signal library</div>
          <div class="text-xs text-ink-500 mb-4">Rules that translate events into signals.</div>
          <div class="space-y-2 max-h-[280px] overflow-y-auto">
            <div v-for="d in defs" :key="d.id" class="flex items-start gap-3 p-2 rounded-lg hover:bg-ink-50">
              <button
                @click="toggleDef(d)"
                class="mt-0.5 w-9 h-5 rounded-full relative transition"
                :class="d.enabled ? 'bg-accent-500' : 'bg-ink-200'">
                <span class="absolute top-0.5 w-4 h-4 rounded-full bg-white shadow transition" :style="{ left: d.enabled ? '18px' : '2px' }"></span>
              </button>
              <div class="flex-1 min-w-0">
                <div class="text-sm font-medium text-ink-900 truncate">{{ d.label }}</div>
                <div class="text-[11px] text-ink-500 line-clamp-2">{{ d.description }}</div>
                <div class="mt-1 inline-flex text-[10px] font-semibold px-1.5 py-0.5 rounded-full bg-ink-100 text-ink-700 capitalize">{{ d.category }}</div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="card p-6">
        <div class="flex items-center justify-between mb-4 gap-3 flex-wrap">
          <div>
            <div class="font-semibold text-ink-900">Active signals</div>
            <div class="text-xs text-ink-500">Live behavioural flags — most recent first.</div>
          </div>
          <div class="flex items-center gap-2">
            <select v-model="filterKey" class="input !py-1.5 !text-xs !w-44">
              <option value="">All signals</option>
              <option v-for="d in defs" :key="d.key" :value="d.key">{{ d.label }}</option>
            </select>
          </div>
        </div>
        <div v-if="!filteredSignals.length" class="text-sm text-ink-500 py-8 text-center">
          No open signals match this filter.
        </div>
        <div v-else class="divide-y divide-ink-100">
          <div v-for="s in pagedSignals" :key="s.id" class="py-3 flex items-start gap-4">
            <div class="w-10 h-10 rounded-lg flex items-center justify-center shrink-0" :style="{ background: colorFor(s.category)+'22', color: colorFor(s.category) }">
              <Icon :name="iconFor(s.category)" class="w-4 h-4"/>
            </div>
            <div class="flex-1 min-w-0">
              <div class="flex items-center gap-2 flex-wrap">
                <div class="font-medium text-ink-900 truncate">{{ s.signal_label || s.signal_key }}</div>
                <span class="chip text-[10px] capitalize" :style="{ background: colorFor(s.category)+'22', color: colorFor(s.category) }">{{ s.category }}</span>
                <span class="chip text-[10px] bg-ink-100 text-ink-700">confidence {{ Math.round(Number(s.confidence)*100) }}%</span>
              </div>
              <div class="text-xs text-ink-500 mt-0.5">
                <NuxtLink v-if="customers[s.customer_id]" :to="`/customers/${s.customer_id}`" class="font-medium text-brand-500 hover:underline">
                  {{ customers[s.customer_id].email || customers[s.customer_id].first_name || 'Customer' }}
                </NuxtLink>
                <span v-else class="font-mono">{{ s.customer_id.slice(0,8) }}</span>
                · detected {{ timeAgo(s.detected_at) }}
              </div>
            </div>
            <div class="flex items-center gap-1">
              <button class="btn-ghost text-xs" @click="recommendOne(s)" :disabled="busy.one === s.id">
                <Icon name="flask" class="w-3 h-3"/>{{ busy.one === s.id ? 'Thinking…' : 'Recommend' }}
              </button>
              <button class="btn-ghost text-xs text-ink-500" @click="dismiss(s)">Dismiss</button>
            </div>
          </div>
        </div>
        <Pagination v-model:page="signalsPage" v-model:pageSize="signalsPageSize" :total="filteredSignals.length"/>
      </div>

      <div class="card p-6">
        <div class="flex items-center justify-between mb-4">
          <div>
            <div class="font-semibold text-ink-900">AI recommendations</div>
            <div class="text-xs text-ink-500">Context-aware next-best messages per customer.</div>
          </div>
          <div class="text-[11px] text-ink-500" v-if="lastModel">Last run model: <span class="font-mono">{{ lastModel }}</span></div>
        </div>
        <div v-if="bulkGroups.length" class="mb-4 rounded-xl border border-brand-500/20 bg-brand-500/5 p-4">
          <div class="flex items-center gap-2 mb-2">
            <Icon name="flask" class="w-4 h-4 text-brand-500"/>
            <div class="font-semibold text-ink-900 text-sm">Group similar recommendations</div>
          </div>
          <div class="text-xs text-ink-600 mb-3">Ship one campaign to everyone flagged by the same signal — faster than drafting one at a time.</div>
          <div class="space-y-2">
            <div v-for="g in bulkGroups" :key="g.key" class="flex items-center gap-3 bg-white rounded-lg border border-ink-100 p-3">
              <div class="flex-1 min-w-0">
                <div class="text-sm font-medium text-ink-900 truncate">{{ g.label }}</div>
                <div class="text-[11px] text-ink-500">{{ g.count }} customers · channel {{ g.channel }} · {{ g.sampleHeadline }}</div>
              </div>
              <button class="btn-primary text-xs" :disabled="busy.bulk === g.key" @click="draftBulkCampaign(g)">
                <Icon name="send" class="w-3 h-3"/>{{ busy.bulk === g.key ? 'Drafting…' : 'Draft bulk campaign' }}
              </button>
            </div>
          </div>
        </div>
        <div v-if="!recos.length" class="text-sm text-ink-500 py-8 text-center">
          No recommendations yet. Click <span class="font-medium">Generate AI recommendations</span> to let Claude draft next-best actions.
        </div>
        <div v-else class="grid md:grid-cols-2 gap-4">
          <div v-for="r in recos" :key="r.id" class="border border-ink-100 rounded-xl p-4 hover:shadow-sm transition">
            <div class="flex items-start justify-between gap-2 mb-2">
              <div class="flex items-center gap-2 flex-wrap">
                <span class="chip text-[10px] bg-brand-500/10 text-brand-500 capitalize">{{ r.channel }}</span>
                <span class="chip text-[10px] bg-accent-500/10 text-accent-500 capitalize">{{ r.kind }}</span>
                <span v-if="r.signal_key" class="chip text-[10px] bg-ink-100 text-ink-700">{{ r.signal_key }}</span>
              </div>
              <div class="text-[10px] text-ink-400">{{ Math.round(Number(r.confidence)*100) }}%</div>
            </div>
            <div class="font-semibold text-ink-900">{{ r.headline }}</div>
            <div class="text-sm text-ink-700 mt-1">{{ r.body }}</div>
            <button v-if="r.cta" class="mt-2 chip bg-brand-500 text-white text-[11px]">{{ r.cta }}</button>
            <div v-if="r.reasoning" class="mt-3 text-[11px] text-ink-500 italic">“{{ r.reasoning }}”</div>
            <div v-if="r.campaign_id && attribution[r.campaign_id]" class="mt-3 flex items-center gap-2 flex-wrap text-[10px]">
              <span class="chip bg-ink-100 text-ink-700">sent {{ attribution[r.campaign_id].sent }}</span>
              <span class="chip bg-brand-100/40 text-brand-700">opens {{ attribution[r.campaign_id].opened }}</span>
              <span class="chip bg-accent-500/10 text-accent-600">clicks {{ attribution[r.campaign_id].clicked }}</span>
              <span v-if="attribution[r.campaign_id].converted" class="chip bg-accent-500/20 text-accent-700 font-semibold">converted {{ attribution[r.campaign_id].converted }}</span>
            </div>
            <div class="mt-3 flex items-center justify-between text-[11px]">
              <NuxtLink v-if="customers[r.customer_id]" :to="`/customers/${r.customer_id}`" class="text-brand-500 hover:underline truncate max-w-[160px]">
                {{ customers[r.customer_id].email || 'Customer' }}
              </NuxtLink>
              <div class="flex items-center gap-1">
                <NuxtLink
                  v-if="r.campaign_id"
                  :to="`/campaigns?id=${r.campaign_id}`"
                  class="btn-ghost text-[11px] text-brand-500"
                >
                  <Icon name="send" class="w-3 h-3"/>Open campaign
                </NuxtLink>
                <button
                  v-else
                  class="btn-ghost text-[11px] text-brand-500"
                  :disabled="busy.draft === r.id"
                  @click="draftCampaign(r)"
                >
                  <Icon name="send" class="w-3 h-3"/>{{ busy.draft === r.id ? 'Drafting…' : 'Draft campaign' }}
                </button>
                <button class="btn-ghost text-[11px]" @click="markStatus(r,'delivered')" :disabled="r.status === 'delivered'">
                  <Icon name="check" class="w-3 h-3"/>Mark delivered
                </button>
                <button class="btn-ghost text-[11px] text-ink-500" @click="markStatus(r,'dismissed')">
                  <Icon name="x" class="w-3 h-3"/>Dismiss
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({ layout: 'default' })
const { supabase, auth, workspaceId } = useWorkspace()
const toast = useToast()
const readiness = useChannelReadiness()

const readinessChannels = computed(() => {
  const channels = new Set<'email'|'push'|'sms'|'inapp'|'webhook'>()
  for (const r of recos.value) {
    const ch = (r.channel || 'email') as any
    if (['email','push','sms','inapp'].includes(ch)) channels.add(ch)
  }
  if (!channels.size) channels.add('email')
  return Array.from(channels)
})

const defs = ref<any[]>([])
const signals = ref<any[]>([])
const recos = ref<any[]>([])
const customers = ref<Record<string, any>>({})
const filterKey = ref('')
const lastModel = ref('')

const busy = reactive<{ detect: boolean; reco: boolean; one: string | null; draft: string | null; bulk: string | null }>({
  detect: false,
  reco: false,
  one: null,
  draft: null,
  bulk: null,
})
const router = useRouter()
const attribution = ref<Record<string, { sent: number; opened: number; clicked: number; converted: number }>>({})

const bulkGroups = computed(() => {
  const map = new Map<string, any[]>()
  for (const r of recos.value) {
    if (r.status !== 'pending' || r.campaign_id) continue
    const key = `${r.signal_key || r.kind || 'unknown'}::${r.channel || 'email'}`
    if (!map.has(key)) map.set(key, [])
    map.get(key)!.push(r)
  }
  const out: any[] = []
  for (const [key, arr] of map.entries()) {
    if (arr.length < 2) continue
    const [signal, channel] = key.split('::')
    out.push({
      key,
      signal,
      channel,
      count: arr.length,
      items: arr,
      sampleHeadline: arr[0].headline,
      label: `${signal.replace(/_/g, ' ')} · ${arr.length} similar recommendations`,
    })
  }
  return out.sort((a, b) => b.count - a.count)
})

const signalsPage = ref(1)
const signalsPageSize = ref(25)
const openSignals = computed(() => signals.value.filter(s => !s.consumed_at))
const pagedSignals = computed(() => {
  const start = (signalsPage.value - 1) * signalsPageSize.value
  return filteredSignals.value.slice(start, start + signalsPageSize.value)
})
watch([() => signals.value.length, () => filterKey.value, signalsPageSize], () => { signalsPage.value = 1 })
const filteredSignals = computed(() => {
  const base = openSignals.value
  return filterKey.value ? base.filter(s => s.signal_key === filterKey.value) : base
})

const stats = computed(() => ({
  open: openSignals.value.length,
  customers: new Set(openSignals.value.map(s => s.customer_id)).size,
  recos: recos.value.length,
  converted: recos.value.filter(r => r.status === 'converted').length,
}))

const categoryBreakdown = computed(() => {
  const map = new Map<string, number>()
  for (const s of openSignals.value) map.set(s.category, (map.get(s.category) || 0) + 1)
  return Array.from(map.entries())
    .map(([key, count]) => ({ key, count, color: colorFor(key) }))
    .sort((a, b) => b.count - a.count)
})
const maxCategory = computed(() => Math.max(1, ...categoryBreakdown.value.map(c => c.count)))

function colorFor(cat: string) {
  switch (cat) {
    case 'commerce': return '#26C165'
    case 'retention': return '#F59E0B'
    case 'lifecycle': return '#3087B9'
    case 'product': return '#0EA5E9'
    case 'engagement': return '#10B981'
    default: return '#6B7280'
  }
}
function iconFor(cat: string) {
  switch (cat) {
    case 'commerce': return 'box'
    case 'retention': return 'clock'
    case 'lifecycle': return 'trending'
    case 'product': return 'layers'
    default: return 'activity'
  }
}

async function loadAll() {
  if (!workspaceId.value) return
  const [defsRes, sigRes, recoRes] = await Promise.all([
    supabase.from('signal_definitions').select('*').eq('workspace_id', workspaceId.value).order('priority', { ascending: false }),
    supabase.from('customer_signals').select('*').eq('workspace_id', workspaceId.value).is('consumed_at', null).order('detected_at', { ascending: false }).limit(1000),
    supabase.from('ai_recommendations').select('*').eq('workspace_id', workspaceId.value).order('created_at', { ascending: false }).limit(50),
  ])
  defs.value = defsRes.data || []
  signals.value = sigRes.data || []
  recos.value = recoRes.data || []
  const ids = Array.from(new Set([
    ...signals.value.map(s => s.customer_id),
    ...recos.value.map(r => r.customer_id),
  ]))
  if (ids.length) {
    const { data } = await supabase.from('customers').select('id,email,first_name,last_name').in('id', ids)
    customers.value = Object.fromEntries((data || []).map(c => [c.id, c]))
  }
  if (recos.value.length) lastModel.value = recos.value[0].model
  await loadAttribution()
}

async function loadAttribution() {
  const campaignIds = Array.from(new Set(recos.value.map(r => r.campaign_id).filter(Boolean))) as string[]
  if (!campaignIds.length) { attribution.value = {}; return }
  const { data } = await supabase
    .from('campaign_messages')
    .select('campaign_id,status,opened_at,clicked_at')
    .in('campaign_id', campaignIds)
  const agg: Record<string, { sent: number; opened: number; clicked: number; converted: number }> = {}
  for (const id of campaignIds) agg[id] = { sent: 0, opened: 0, clicked: 0, converted: 0 }
  for (const m of data || []) {
    const a = agg[m.campaign_id]
    if (!a) continue
    a.sent += 1
    if (m.opened_at) a.opened += 1
    if (m.clicked_at) { a.clicked += 1; a.converted += 1 }
  }
  attribution.value = agg
}

async function runDetect() {
  if (!workspaceId.value) return
  busy.detect = true
  try {
    const { data, error } = await supabase.rpc('detect_workspace_signals', { p_workspace_id: workspaceId.value })
    if (error) throw error
    if (!data?.ok) throw new Error(data?.error || 'failed')
    toast.success('Scan complete', `Scanned ${data.events_scanned} events across ${data.customers_touched} customers.`)
    await loadAll()
  } catch (e: any) {
    toast.error('Scan failed', e.message || 'Try again.')
  } finally {
    busy.detect = false
  }
}

async function callAiFn(body: any) {
  const url = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/ai-recommend`
  const { data: { session } } = await supabase.auth.getSession()
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${session?.access_token || import.meta.env.VITE_SUPABASE_ANON_KEY}`,
      'apikey': import.meta.env.VITE_SUPABASE_ANON_KEY,
    },
    body: JSON.stringify(body),
  })
  const json = await res.json().catch(() => ({}))
  if (!res.ok || !json.ok) throw new Error(json.error || `HTTP ${res.status}`)
  return json
}

async function runRecommend() {
  if (!workspaceId.value) return
  busy.reco = true
  try {
    const json = await callAiFn({ workspace_id: workspaceId.value, limit: 15 })
    lastModel.value = json.used_model
    if (json.insert_error) {
      toast.error('Insert failed', json.insert_error)
    } else if (json.created === 0 && json.signals_considered > 0) {
      toast.error('No recommendations created', `Claude errors: ${json.claude_errors || 0}. Signals: ${json.signals_considered}.`)
    } else {
      toast.success('Recommendations ready', `${json.created} drafted by ${json.used_model}.`)
    }
    await loadAll()
  } catch (e: any) {
    toast.error('Could not generate', e.message || 'Try again.')
  } finally {
    busy.reco = false
  }
}

async function recommendOne(s: any) {
  if (!workspaceId.value) return
  busy.one = s.id
  try {
    await callAiFn({ workspace_id: workspaceId.value, signal_ids: [s.id], limit: 1 })
    toast.success('Recommendation drafted')
    await loadAll()
  } catch (e: any) {
    toast.error('Failed', e.message)
  } finally {
    busy.one = null
  }
}

async function dismiss(s: any) {
  await supabase.from('customer_signals').update({ consumed_at: new Date().toISOString(), consumed_by: 'dismissed' }).eq('id', s.id)
  signals.value = signals.value.filter(x => x.id !== s.id)
}

async function draftCampaign(r: any) {
  if (!workspaceId.value) return
  const ch = (r.channel || 'email') as any
  const status = readiness.status(ch)
  if (status && status.blockers.length) {
    toast.error(`${ch.toUpperCase()} not ready`, status.blockers[0].reason + ' — ' + status.blockers[0].fix)
    return
  }
  busy.draft = r.id
  try {
    const cust = customers.value[r.customer_id]
    const label = cust?.email || cust?.first_name || 'Customer'
    const headline = (r.headline || 'AI recommendation').slice(0, 80)

    const { data: list, error: listErr } = await supabase.from('lists').insert({
      workspace_id: workspaceId.value,
      name: `AI: ${headline} -> ${label}`.slice(0, 120),
      description: `Auto-generated from AI recommendation (${r.signal_key || r.kind}).`,
      type: 'static',
    }).select('id').maybeSingle()
    if (listErr || !list) throw listErr || new Error('Could not create list')

    const { error: memberErr } = await supabase.from('list_members').insert({
      list_id: list.id,
      customer_id: r.customer_id,
    })
    if (memberErr) throw memberErr

    const body = r.cta ? `${r.body}\n\nCTA: ${r.cta}` : r.body
    const { data: camp, error: campErr } = await supabase.from('campaigns').insert({
      workspace_id: workspaceId.value,
      name: `AI reco: ${headline}`.slice(0, 120),
      channel: r.channel || 'email',
      status: 'draft',
      subject: headline,
      content: body,
      audience_type: 'list',
      audience_id: list.id,
    }).select('id').maybeSingle()
    if (campErr || !camp) throw campErr || new Error('Could not create campaign')

    const { error: updErr } = await supabase.from('ai_recommendations').update({
      status: 'queued',
      campaign_id: camp.id,
    }).eq('id', r.id)
    if (updErr) throw updErr

    r.campaign_id = camp.id
    r.status = 'queued'
    toast.success('Draft campaign created', 'Review and schedule it on the Campaigns page.')
    router.push(`/campaigns?id=${camp.id}`)
  } catch (e: any) {
    toast.error('Could not draft campaign', e.message || 'Try again.')
  } finally {
    busy.draft = null
  }
}

async function draftBulkCampaign(group: any) {
  if (!workspaceId.value) return
  const ch = (group.channel || 'email') as any
  const status = readiness.status(ch)
  if (status && status.blockers.length) {
    toast.error(`${ch.toUpperCase()} not ready`, status.blockers[0].reason + ' — ' + status.blockers[0].fix)
    return
  }
  busy.bulk = group.key
  try {
    const items = group.items as any[]
    const signalLabel = (group.signal as string).replace(/_/g, ' ')
    const headline = items[0].headline || `Nudge for ${signalLabel}`
    const body = items[0].cta ? `${items[0].body}\n\nCTA: ${items[0].cta}` : items[0].body

    const { data: list, error: listErr } = await supabase.from('lists').insert({
      workspace_id: workspaceId.value,
      name: `AI bulk: ${signalLabel} (${items.length})`.slice(0, 120),
      description: `Auto-generated from ${items.length} AI recommendations for signal ${group.signal}.`,
      type: 'static',
    }).select('id').maybeSingle()
    if (listErr || !list) throw listErr || new Error('Could not create list')

    const uniqueCustomers = Array.from(new Set(items.map((i: any) => i.customer_id)))
    const memberRows = uniqueCustomers.map(cid => ({ list_id: list.id, customer_id: cid }))
    const { error: memberErr } = await supabase.from('list_members').insert(memberRows)
    if (memberErr) throw memberErr

    const { data: camp, error: campErr } = await supabase.from('campaigns').insert({
      workspace_id: workspaceId.value,
      name: `AI bulk: ${signalLabel}`.slice(0, 120),
      channel: group.channel || 'email',
      status: 'draft',
      subject: headline,
      content: body,
      audience_type: 'list',
      audience_id: list.id,
    }).select('id').maybeSingle()
    if (campErr || !camp) throw campErr || new Error('Could not create campaign')

    const ids = items.map((i: any) => i.id)
    const { error: updErr } = await supabase.from('ai_recommendations').update({
      status: 'queued',
      campaign_id: camp.id,
    }).in('id', ids)
    if (updErr) throw updErr

    for (const r of recos.value) {
      if (ids.includes(r.id)) { r.status = 'queued'; r.campaign_id = camp.id }
    }
    toast.success('Bulk campaign drafted', `${uniqueCustomers.length} recipients queued — review and schedule.`)
    router.push(`/campaigns?id=${camp.id}`)
  } catch (e: any) {
    toast.error('Could not draft bulk campaign', e.message || 'Try again.')
  } finally {
    busy.bulk = null
  }
}

async function markStatus(r: any, status: string) {
  const patch: any = { status }
  if (status === 'delivered') patch.delivered_at = new Date().toISOString()
  if (status === 'converted') patch.converted_at = new Date().toISOString()
  if (status === 'dismissed') patch.dismissed_at = new Date().toISOString()
  await supabase.from('ai_recommendations').update(patch).eq('id', r.id)
  r.status = status
}

async function toggleDef(d: any) {
  const next = !d.enabled
  d.enabled = next
  await supabase.from('signal_definitions').update({ enabled: next }).eq('id', d.id)
}

watch(workspaceId, loadAll, { immediate: true })
</script>
